apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-go
  template:
    metadata:
      labels:
        app: guestbook-go
    spec:
      containers:
        - name: guestbook-go
          image: rg560237/guestbook-go:latest
          ports:
            - containerPort: 8080
