name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/guestbook-go:latest --push .
